config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :visits, except: [:edit, :update]
  resources :doctors
  root 'clinic#index', as: 'clinic_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/visit.rb
class Visit < ApplicationRecord
  #minimal interval to cancel the visit - 1 hour
  CANCEL_TIME = 3600

  before_destroy :ensure_that_can_be_canceled
  belongs_to :doctor
  belongs_to :user
  validates :start_time, :end_time, presence: true
  validates_with TimeSlotValidator
  validates_with FreeSlotValidator

  private

  def ensure_that_can_be_canceled
    if (start_time - DateTime.now).to_i < CANCEL_TIME
      errors.add(:base, "Less #{CANCEL_TIME / 60} than minutes left to an appointment.")
      throw :abort
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    if @current_user.is_admin
      @visits = Visit.order(start_time: :desc)
    else
      @visits = Visit.where(user_id: @current_user).order(start_time: :desc)

    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    unless @current_user.is_admin
      redirect_to visits_url
    end
  end

  # GET /visits/new
  def new
    @doctor = Doctor.find_by_id(params[:doctor_id])
    @doctor_visits = Visit.where(doctor_id: params[:doctor_id], start_time: DateTime.now..DateTime.now.next_year)
    @visit = Visit.new
  end


  # GET /visits/1/edit
  # def edit
  #   unless @current_user.is_admin || session[:user_id] == @visit.user_id
  #     redirect_to @current_user
  #   end
  # end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)
    @visit.user_id = @current_user.id

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new, params: { doctor_id: 3 } }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  # def update
  #   if @current_user.is_admin || session[:user_id] == @visit.user_id
  #     respond_to do |format|
  #       if @visit.update(visit_params)
  #         format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
  #         format.json { render :show, status: :ok, location: @visit }
  #       else
  #         format.html { render :edit }
  #         format.json { render json: @visit.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   else
  #     redirect_to @current_user
  #   end
  # end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    if @current_user.is_admin || session[:user_id] == @visit.user_id
      if @visit.destroy
        respond_to do |format|
          format.html { redirect_to visits_url, notice: 'Visit was successfully canceled.' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to visits_path, alert: "Visit can't be canceled. #{@visit.errors[:base][-1]}"}
        end
      end
    else
      redirect_to visits_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visit_params
      params.require(:visit).permit(:doctor_id, :start_time, :end_time)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_with(model: visit, local: true) do |form| %>
  <% if visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
        <% visit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @doctor %>
  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.select :doctor_id, Doctor.all.order(:surname).map{ |doc| ["#{doc.surname} #{doc.name}", doc.id]},
        selected: (doctor.id if doctor) %>
  </div>
  <% end %>

  <% unless @doctor %>
    <div class="field">
      <%= form.label :doctor_id %>
      <%= form.select :doctor_id, Doctor.all.order(:surname).map{ |doc| ["#{doc.surname} #{doc.name}", doc.id]}%>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, default: 1.hours.from_now, minute_step: 5,
                             start_year:Date.today.year, end_year: Date.today.year + 1 %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, default: 1.hours.from_now, minute_step: 5,
                             start_year:Date.today.year, end_year: Date.today.year + 1 %>
  </div>


  <div class="actions">
    <%= form.submit 'Confirm an appointment', class: 'btn btn-outline-success btn-sm' %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<aside id="notice"><%= notice %></aside>
<aside style="color:red;"><%= alert %></aside>

<h1>Visits:</h1>
<% if @visits.empty? %>
  <h4>You don't have visits right now:</h4>
<% end %>
<% unless @visits.empty? %>
<table class="table">
  <thead>
    <tr>
      <th>Doctor</th>
      <th>User</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <% dt_format = "%d-%m-%Y %H:%M" %>
        <td><%= "#{visit.doctor.name} #{visit.doctor.surname}" %></td>
        <td><%= "#{visit.user.name} #{visit.user.surname}" %></td>
        <td><%= visit.start_time.strftime(dt_format) %></td>
        <td><%= visit.end_time.strftime(dt_format) %></td>
        <% if @current_user.is_admin %>
        <td><%= link_to 'Show', visit, class: 'btn btn-outline-primary btn-sm' %></td>
        <% end %>
        <td><%= link_to 'Cancel', visit, method: :delete, data: { confirm: 'Are you sure?' },
                        class: 'btn btn-outline-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>


<%= link_to 'New Visit', new_visit_path, class: 'btn btn-outline-success btn-sm' %>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form', visit: @visit, doctor: @doctor %>

<%= link_to 'Back', visits_path, class: 'btn btn-outline-secondary btn-sm'%>

<% if @doctor %>
  <h1>Doctor <%= @doctor.surname %> visits:</h1>
  <% if @doctor_visits.empty? %>
    <h3>Doctor <%= @doctor.surname %> doesn't have visits yet.</h3>
  <% end %>
  <% @doctor_visits.each do |visit| %>
    <tr>
      <td><h4><%= visit.start_time.strftime("%d.%m.%y %H:%M") %> - <%=visit.end_time.strftime("%H:%M") %></h4></td>
    </tr>
  <% end %>
<% end %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @visit.doctor.name %> <%= @visit.doctor.surname %>
</p>

<p>
  <strong>User:</strong>
  <%= @visit.user.name %> <%= @visit.user.surname %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @visit.start_time.strftime("%d.%m.%Y %H:%M") %>
</p>

<p>
  <strong>End time:</strong>
  <%= @visit.end_time.strftime("%d.%m.%Y %H:%M") %>
</p>

<%= link_to 'Back', visits_path, class: 'btn btn-outline-secondary btn-sm' %> |
<%= link_to 'Destroy', @visit, method: :delete, data: { confirm: 'Are you sure?' },
            class: 'btn btn-outline-danger btn-sm' %>