config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :visits, except: [:edit, :update]
  resources :doctors
  root 'clinic#index', as: 'clinic_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates :name, :surname, presence: true
  validates :phone_number, uniqueness: true
  validates :phone_number, allow_blank: true, format:{
      with: /\A\d{10,13}\z/,
      message: 'Phone number has 10-13 digits'
  }
  validates :work_hours, allow_blank: true, format:{
      with: /\A([0-1]\d|2[0-3]):[0-5][0,5]\s-\s([0-1]\d|2[0-3]):[0-5][0,5]\z/,
      message: '00:00 - 23:55 format with step 5 min'
  }

  has_many :visits
  before_destroy :ensure_no_visits_for_doctor

  private

  def ensure_no_visits_for_doctor
    unless visits.empty?
      errors.add(:base, 'Doctor has visits')
      throw :abort
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.order(:name)
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    if @current_user.is_admin
      @visits = Visit.order(start_time: :desc).where(doctor_id: @doctor)
    else
      redirect_to doctors_url
    end
  end

  # GET /doctors/new
  def new
    if @current_user.is_admin
      @doctor = Doctor.new
    else
      redirect_to doctors_url
    end
  end

  # GET /doctors/1/edit
  def edit
    unless @current_user.is_admin
      redirect_to doctors_url
    end
  end

  # POST /doctors
  # POST /doctors.json
  def create
    if @current_user.is_admin
      @doctor = Doctor.new(doctor_params)
      respond_to do |format|
        if @doctor.save
          format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
          format.json { render :show, status: :created, location: @doctor }
        else
          format.html { render :new }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to doctors_url
    end



  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    if @current_user.is_admin
      respond_to do |format|
        if @doctor.update(doctor_params)
          format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
          format.json { render :show, status: :ok, location: @doctor }
        else
          format.html { render :edit }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to doctors_url
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    if @current_user.is_admin
      if @doctor.destroy
        respond_to do |format|
          format.html { redirect_to doctors_url, notice: 'Doctor was successfully deleted.' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to doctors_path, alert: "Doctor can't be deleted. #{@doctor.errors[:base][-1]}"}
        end
      end
    else
      redirect_to doctors_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :surname, :specialization, :phone_number, :work_hours, :photo_url)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :specialization %>
    <%= form.text_field :specialization %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.telephone_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :work_hours %>
    <%= form.text_field :work_hours %>
  </div>

  <div class="field">
    <%= form.label :photo_url %>
    <%= form.url_field :photo_url %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-outline-success btn-sm' %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor, class: 'btn btn-outline-primary btn-sm' %>
<%= link_to 'Back', doctors_path, class: 'btn btn-outline-secondary btn-sm' %>

app/views/doctors/index.html.erb
<aside id="notice"><%= notice %></aside>
<aside style="color:red;"><%= alert %></aside>

<h1>Doctors</h1>
<table class="table">
  <% if @current_user.is_admin %>
    <tfoot>
    <tr>
        <td colspan="3">
            <%= link_to 'New Doctor', new_doctor_path, class: 'btn btn-outline-success btn-sm' %>
        </td>
    </tr>
    </tfoot>
  <% end %>
    <tbody>
    <% @doctors.each do |doctor| %>
    <tr>
        <td class="image">
            <%= image_tag(doctor.photo_url, class: 'list_image') %>
        </td>
        <td class="description">
            <h1><%= "#{doctor.name} #{doctor.surname}" %></h1>
            <p>
                <%= doctor.specialization.capitalize %>
            </p>
            <p>
            <%= doctor.work_hours %>
            </p>
          <p>
            <%= "Tel. #{doctor.phone_number}" %>
          </p>
        </td>
      <% if @current_user.is_admin %>
        <td class="actions">
            <ul>
                <li><%= link_to 'Show', doctor, class: 'btn btn-outline-primary btn-sm' %></li>
                <li><%= link_to 'Edit', edit_doctor_path(doctor), class: 'btn btn-outline-warning btn-sm' %></li>
                <li>
                    <%= link_to 'Delete',
                                doctor,
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-outline-danger btn-sm'%>
                </li>
            </ul>
        </td>
        <% end %>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @doctor.surname %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @doctor.specialization %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @doctor.phone_number %>
</p>

<p>
  <strong>Work hours:</strong>
  <%= @doctor.work_hours %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @doctor.photo_url %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor), class: 'btn btn-outline-warning btn-sm' %> |
<%= link_to 'Back', doctors_path, class: 'btn btn-outline-secondary btn-sm' %>

<h1>Doctor's visits</h1>

<table class="table">
  <thead>
  <tr>
    <th>User</th>
    <th>Start time</th>
    <th>End time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @visits.each do |visit| %>
    <tr>
      <% dt_format = "%d-%m-%Y %H:%M" %>
      <td><%= "#{visit.user.name} #{visit.user.surname}" %></td>
      <td><%= visit.start_time.strftime(dt_format) %></td>
      <td><%= visit.end_time.strftime(dt_format) %></td>
      <td><%= link_to 'Show', visit, class: 'btn btn-outline-primary btn-sm' %></td>
      <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' },
                      class: 'btn btn-outline-danger btn-sm' %></td>
    </tr>
  <% end %>
  </tbody>
</table>