config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :visits, except: [:edit, :update]
  resources :doctors
  root 'clinic#index', as: 'clinic_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Healthbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>
    <header class="main">
      <%= image_tag 'logo.png', alt: 'Health Book' %>
      <% if @current_user && @current_user.is_admin %>
        <h6 style="text-align: right; color: blue; margin-right: 1em">You logged in as admin!</h6>
      <% end %>
      <h1><%= @page_title %></h1>
    </header>
    <section class="content">
    <nav class="side_nav">
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/">News</a></li>
        <li><a href="/">Contact</a></li>
      </ul>

      <% if session[:user_id] %>
        <nav class="logged_in_nav">
      <ul>
      <li><%= link_to 'Doctors', doctors_path %></li>
      <li><%= link_to 'Account', users_path %></li>
      <li><%= link_to 'Visits', visits_path %></li>
      <li><%= button_to 'Logout', logout_path, method: :delete %></li>
      </ul>
      </nav>
        <% end %>
      <% unless session[:user_id] %>
        <nav class="logged_in_nav">
          <ul>
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Sign Up', new_user_path %></li>
          </ul>
        </nav>
      <% end %>
    </nav>
    <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>
    </section>
  </body>
</html>